
-- EXERCICIOS DE SQL SERVER --

-- QUESTÃO 01: CRIE UMA TABELA COM 4 COLUNAS (NOME) (CPF) (ANO) (MÊS)

CREATE TABLE TB_PESSOA(

	Nome VARCHAR(50),
	CPF NUMERIC(11),
	Ano NUMERIC(4),
	Mes INT
);

SELECT * FROM TB_PESSOA


-- QUESTÃO 02: INSIRA DADOS NA TABELA COM 4 LINHAS

INSERT INTO TB_PESSOA (Nome, CPF, Ano, Mes)
VALUES
('João Santos Silva', '12345678911', '1995', '07'),
('Ana Santos Silva', '45678912311', '1998', '02'),
('Pedro Santos', '78912345611', '1999', '04'),
('Maria Silva', '12345678999', '2000', '11')

SELECT * FROM TB_PESSOA


-- QUESTÃO 03: DELETE A TABELA E CRIE DE NOVO A MESMA TABELA

DROP TABLE TB_PESSOA

SELECT * FROM TB_PESSOA

CREATE TABLE TB_PESSOA(
	
	Nome VARCHAR(50),
	CPF NUMERIC(11),
	Ano NUMERIC(4),
	Mes INT
);

SELECT * FROM TB_PESSOA

INSERT INTO TB_PESSOA (Nome, CPF, Ano, Mes)
VALUES
('João Santos Silva', '12345678911', '1995', '07'),
('Ana Santos Silva', '45678912311', '1998', '02'),
('Pedro Santos', '78912345611', '1999', '04'),
('Maria Silva', '12345678999', '2000', '11')

SELECT * FROM TB_PESSOA


-- QUESTÃO 04: FAÇA UM FILTRO QUE MOSTRE SOMENTES OS NOMES

SELECT Nome FROM TB_PESSOA


-- QUESTÃO 05: FAÇA UM FILTRO QUE MOSTRE SOMENTE O CPF

SELECT CPF FROM TB_PESSOA


-- QUESTÃO 06: FAÇA UM FILTRO QUE MOSTRE SOMENTE O MÊS

SELECT Mes FROM TB_PESSOA


-- QUESTÃO 07: FAÇA UM FILTRO ONDE SOMENTE MOSTRE O ANO

SELECT Ano FROM TB_PESSOA


-- QUESTÃO 08: FAÇA UM FILTRO QUE MOSTRE SOMENTE UM NOME NO QUAL O MESMO FOR REPETIDO (USE O DISTINCT)

SELECT * FROM TB_PESSOA

INSERT INTO TB_PESSOA (Nome, CPF, Ano, Mes)
VALUES
('João Santos Silva', '12345678911', '1995', '07')

SELECT * FROM TB_PESSOA

SELECT DISTINCT Nome FROM TB_PESSOA


-- QUESTÃO 09: ESCOLHA UMA COLUNA E ALTERE O SEU NOME

SELECT * FROM TB_PESSOA

SELECT Nome AS Titulo FROM TB_PESSOA


-- QUESTÃO 10: FAÇA ALGUNS FILTROS QUE ME RETORNEM OS SEGUINTES DADOS:
-- NOME RAFAEL CPF FINAL 24 ANO DE 2020 MÊS 1

SELECT * FROM TB_PESSOA

INSERT INTO TB_PESSOA (Nome, CPF, Ano, Mes)
VALUES
('Rafael Souza', '12345678924', '2020', '01')

SELECT Nome, CPF, Ano, Mes FROM TB_PESSOA
WHERE 
	Nome LIKE '%Rafael%' AND
	CPF LIKE '%24%' AND
	Ano = '2020' AND
	Mes = '01';
